d=[]
name=input("enter the name").split('=')
d.append(name)
age=input("enter the age").split('=')
d.append(age)
country=input("enter the country").split('=')
d.append(country)
language=input("enter the language ").split('=')
d.append(language)
address=input("enter the address".split('=')
d.append(address)
print(d)
z=dict(d)
print(z)
